### ISSUE TITLE
is it possible that client work  parallelly?

### ISSUE THREAD

**Issue by kaixinbuyu** [delattj/wsrpc#1]
I test the code in this way:

Server: 10 go routine call Node.WorkFunc(threadId)
Node's WorkFunc:{time.sleep(10 sec);print threadId work done!}

the node client can only process one call per second.

is it possible that call client to work  parallelly?

**Comment by delattj** [comment]
handleRequest uses a `go call` to run the registered function.
It then depends on your code implementation.
You need to leverage goroutine paradigm. ie: https://gobyexample.com/goroutines
